- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: ${RUFF_VERSION}
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      stages: [pre-commit]
    # Run the formatter.
    - id: ruff-format
      stages: [pre-commit]
